version: '2'
services:

  presto-master:
    volumes:
      - ../../../conf/presto/etc/environment-specific-catalogs/singlenode-kerberos-hdfs-impersonation-cross-realm/hive.properties:/docker/presto-product-tests/conf/presto/etc/catalog/hive.properties
