name: cleanup

on:
  # Triggered on every PR merge or close (but with the code and workflow as present in the base of the merge instead of the merge commmit)
  pull_request_target:
    types:
      - closed

# NOTE: Do not check out/execute code from the PR since a read-write token is present due to pull_request_target
jobs:
  cancel:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Cancel Runs For Closed PRs'
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          # Cancel workflow when PR closed. https://github.com/styfle/cancel-workflow-action#advanced-ignore-sha
          ignore_sha: true
          # Note: workflow_id can be a Workflow ID (number) or Workflow File Name (string) or a comma-separated list of those.
          workflow_id: "ci.yml,docs.yml"
          access_token: ${{ github.token }}
